import { InstrumentConfig } from './types';

export const INSTRUMENTS: InstrumentConfig[] = [
  {
    symbol: 'BTCUSDT',
    name: 'Bitcoin / Tether USD',
    category: 'CRYPTO',
    pricePrecision: 2,
    sizePrecision: 4,
    whaleThresholdUsd: 150000,
    isLiveSupported: true,
    basePrice: 94250.00,
  },
  {
    symbol: 'ETHUSDT',
    name: 'Ethereum / Tether USD',
    category: 'CRYPTO',
    pricePrecision: 2,
    sizePrecision: 3,
    whaleThresholdUsd: 100000,
    isLiveSupported: true,
    basePrice: 3420.50,
  },
  {
    symbol: 'SOLUSDT',
    name: 'Solana / Tether USD',
    category: 'CRYPTO',
    pricePrecision: 2,
    sizePrecision: 2,
    whaleThresholdUsd: 50000,
    isLiveSupported: true,
    basePrice: 198.75,
  },
  {
    symbol: 'BNBUSDT',
    name: 'BNB Chain / Tether USD',
    category: 'CRYPTO',
    pricePrecision: 2,
    sizePrecision: 2,
    whaleThresholdUsd: 75000,
    isLiveSupported: true,
    basePrice: 620.00,
  },
  {
    symbol: 'XRPUSDT',
    name: 'XRP / Tether USD',
    category: 'CRYPTO',
    pricePrecision: 4,
    sizePrecision: 1,
    whaleThresholdUsd: 50000,
    isLiveSupported: true,
    basePrice: 2.15,
  },
  {
    symbol: 'DOGEUSDT',
    name: 'Dogecoin / Tether USD',
    category: 'CRYPTO',
    pricePrecision: 5,
    sizePrecision: 0,
    whaleThresholdUsd: 30000,
    isLiveSupported: true,
    basePrice: 0.28,
  },
  {
    symbol: 'ADAUSDT',
    name: 'Cardano / Tether USD',
    category: 'CRYPTO',
    pricePrecision: 4,
    sizePrecision: 1,
    whaleThresholdUsd: 30000,
    isLiveSupported: true,
    basePrice: 0.75,
  },
  {
    symbol: 'AVAXUSDT',
    name: 'Avalanche / Tether USD',
    category: 'CRYPTO',
    pricePrecision: 2,
    sizePrecision: 2,
    whaleThresholdUsd: 40000,
    isLiveSupported: true,
    basePrice: 32.50,
  },
  {
    symbol: 'NVDA',
    name: 'NVIDIA Corp (HFT Equities)',
    category: 'EQUITY',
    pricePrecision: 2,
    sizePrecision: 0,
    whaleThresholdUsd: 250000,
    isLiveSupported: false,
    basePrice: 138.40,
  },
  {
    symbol: 'SPY',
    name: 'SPDR S&P 500 ETF Trust',
    category: 'INDEX',
    pricePrecision: 2,
    sizePrecision: 0,
    whaleThresholdUsd: 300000,
    isLiveSupported: false,
    basePrice: 595.20,
  },
  {
    symbol: 'AAPL',
    name: 'Apple Inc',
    category: 'EQUITY',
    pricePrecision: 2,
    sizePrecision: 0,
    whaleThresholdUsd: 200000,
    isLiveSupported: false,
    basePrice: 232.80,
  },
  {
    symbol: 'EURUSD',
    name: 'Euro / US Dollar FX',
    category: 'FOREX',
    pricePrecision: 5,
    sizePrecision: 0,
    whaleThresholdUsd: 500000,
    isLiveSupported: false,
    basePrice: 1.08450,
  },
];

export function getInstrument(symbol: string): InstrumentConfig {
  return INSTRUMENTS.find(i => i.symbol === symbol) || INSTRUMENTS[0];
}
